Add C4 Engine
SteamDatabase/FileDetectionRuleSets pull request #206
Opened 2023-02-05 20:58 UTC by diedyesterdaywashere

### SteamDB app page links to a few games using this
https://steamdb.info/app/283600/

### Brief explanation of the change

Added C4 Engine detection

2023-02-06 16:17 UTC, Lifeismana requested changes

2023-02-06 16:53 UTC, Lifeismana commented on rules.ini
> +C4Engine = ^Data/C4$
also it seems that this regex isn't "wide" enough, this app https://steamdb.info/app/300160/ doesn't have a folder named C4 but has a file C4.pak (`Data/C4.pak`) (and it does use that engine)

2023-02-06 18:36 UTC, diedyesterdaywashere commented on rules.ini
> +C4Engine = ^Data/C4$
made it just look for anything C4 related since idk how to make multiple rules in one regex

2023-02-07 11:15 UTC, Lifeismana approved these changes

2023-02-07 11:19 UTC, Lifeismana commented
Looks good to me now, thanks for the PR!

2023-02-07 11:20 UTC, merged