Add Arbiter
SteamDatabase/FileDetectionRuleSets pull request #210
Opened 2023-02-06 09:08 UTC by diedyesterdaywashere

### SteamDB app page links to a few games using this

https://steamdb.info/app/1240440/

### Brief explanation of the change

Added Arbiter rules, for now its only used in Halo Infinite but might move onto next Halo games when they get released

2023-02-06 21:57 UTC, Lifeismana requested changes

2023-02-06 21:57 UTC, Lifeismana commented on descriptions/AntiCheat.Arbiter.md
> +Halo Infinite is shipped with its own proprietary anti-cheat system which we call [**Arbiter**](https://www.halowaypoint.com/news/closer-look-halo-infinites-anti-cheat-strategy).
i would prefer something like that
```suggestion
[**Arbiter**](https://www.halowaypoint.com/news/closer-look-halo-infinites-anti-cheat-strategy) is the anti-cheat system used by Halo Infinite.
```

2023-02-06 21:57 UTC, diedyesterdaywashere commented on descriptions/AntiCheat.Arbiter.md
> +Halo Infinite is shipped with its own proprietary anti-cheat system which we call [**Arbiter**](https://www.halowaypoint.com/news/closer-look-halo-infinites-anti-cheat-strategy).
done

2023-02-07 10:57 UTC, Lifeismana approved these changes

2023-02-07 11:01 UTC, merged