PyGame
SteamDatabase/FileDetectionRuleSets pull request #334
Opened 2023-08-17 19:05 UTC by MichaelHinrichs

[**Fine. I'll do it myself.**](https://github.com/SteamDatabase/FileDetectionRuleSets/issues/290)

### SteamDB app page links to a few games using this
https://steamdb.info/app/951360/
https://steamdb.info/app/550900/
https://steamdb.info/app/442210/
https://steamdb.info/app/918170/
https://steamdb.info/app/2363270/
https://steamdb.info/app/660340/
https://steamdb.info/app/1364570/

### Brief explanation of the change
Find PyGame by it's directories and base file.

2023-08-17 19:21 UTC, MichaelHinrichs commented
Found another one.
https://steamdb.info/sub/93793/

2023-08-29 22:45 UTC, MichaelHinrichs commented
Pull my finger.

2024-01-05 12:43 UTC, Lifeismana requested changes
needs some non matching test and the generate strings script to be run

2024-01-05 12:43 UTC, Lifeismana commented on descriptions/Engine.PyGame.md
> +[**PyGame**](https://www.pygame.org/) is a set of highly portable Python libraries designed for writing video games. It runs on almost all OSs and platforms. Pygame is released under the LGPL licence
```suggestion
[**PyGame**](https://www.pygame.org/) is a set of Python modules designed for writing video games.
```

2024-01-05 17:00 UTC, merged