add GDK
SteamDatabase/FileDetectionRuleSets pull request #425
Opened 2023-09-11 20:32 UTC by diedyesterdaywashere

### SteamDB app page links to a few games using this

https://steamdb.info/app/1657630/depots/

### Brief explanation of the change

added a rule for GDK

2023-11-18 18:58 UTC, Lifeismana requested changes
also run the generateTestStrings script

2023-11-18 18:58 UTC, Lifeismana commented on descriptions/SDK.Game_Development_Kit.md
> +The [Microsoft Game Development Kit](https://learn.microsoft.com/en-us/gaming/gdk/) (GDK) is a complete set of tools, APIs, extensions, and programing models that can be used across current and futur
```suggestion
The [**Microsoft Game Development Kit (GDK)**](https://learn.microsoft.com/en-us/gaming/gdk/) is a complete set of tools, APIs, extensions, and programing models that can be used across current and future Microsoft Gaming platforms and initiatives.
```

2023-11-18 18:58 UTC, Lifeismana commented on rules.ini
> +Game_Development_Kit = (?:^|/)(?:XGamingRuntime|XGamingRuntimeThunks|XCurl|Microsoft_Xbox_Services_141_GDK_C_Thunks)\.dll$
```suggestion
Game_Development_Kit = (?:^|/)(?:XGamingRuntime(?:Thunks)?|XCurl|Microsoft_Xbox_Services_141_GDK_C_Thunks)\.dll$
```

2023-11-19 16:25 UTC, diedyesterdaywashere commented
> also run the generateTestStrings script

could you please run it for me? i dont have php installed locally so i can't do that...

or maybe y'all should make an action that would run the generateteststrings thing on pr creation?

2024-02-24 00:20 UTC, merged