Leap
SteamDatabase/FileDetectionRuleSets pull request #496
Opened 2023-10-12 18:54 UTC by MichaelHinrichs

### SteamDB app page links to a few games using this
https://steamdb.info/app/223750/
https://steamdb.info/app/274920/
https://steamdb.info/app/457550/
https://steamdb.info/app/623810/
https://steamdb.info/app/766300/
https://steamdb.info/app/871170/
https://steamdb.info/app/966180/
https://steamdb.info/app/1364390/
https://steamdb.info/app/1435710/
https://steamdb.info/app/1913200/
https://steamdb.info/app/1957330/

### Brief explanation of the change
Add Leap Motion SDK. Closes #475.

2024-01-08 17:28 UTC, Lifeismana requested changes
needs some non matching tests

2024-01-08 17:28 UTC, Lifeismana commented on descriptions/SDK.Leap.md
> +The Leap Motion SDK is a controller-free hand tracking and haptics software by [**Ultraleap**](https://www.ultraleap.com/)
```suggestion
[Leap Motion SDK](https://developer.leapmotion.com/) is a controller-free hand tracking and haptics software by Ultraleap
```

2024-02-01 18:49 UTC, MichaelHinrichs commented
> needs some non matching tests

https://github.com/SteamDatabase/FileDetectionRuleSets/pull/496/commits/7aa24821be8b1a11dcac0123bb2071be5bd3ebe8
How's that?

2024-02-01 18:57 UTC, Lifeismana commented
you don't have to put swear words in your commits

2024-02-04 19:25 UTC, MichaelHinrichs commented
Done.

2024-05-24 14:52 UTC, Lifeismana commented
merged in 6318ab370aa22de152b039381b153497b87600b4

2024-05-24 14:52 UTC, closed without merging