Fase
SteamDatabase/FileDetectionRuleSets pull request #523
Opened 2023-10-19 22:33 UTC by MichaelHinrichs

### SteamDB app page links to a few games using this
https://steamdb.info/app/435030/
https://steamdb.info/app/392950/
https://steamdb.info/app/433000/
https://steamdb.info/app/377450/
https://steamdb.info/app/372940/
https://steamdb.info/app/626640/
https://steamdb.info/app/846690/
https://steamdb.info/app/986820/

### Brief explanation of the change
Find faseEngine.dll.

2023-11-18 18:51 UTC, Lifeismana requested changes

2023-11-18 18:51 UTC, Lifeismana commented on rules.ini
> +Fase = faseEngine\.dll$
```suggestion
Fase = ^faseEngine\.dll$
```

2023-11-18 18:51 UTC, Lifeismana commented on descriptions/Engine.Fase.md
> +It is an engine for sprites, tiles, and maps, made to interface with ZX Basic, C and ASM.
```suggestion
[**Fucking Awesome Spectrum Engine (FASE)**](https://github.com/DSkywalk/fase) is a small open source engine.
```

2023-11-19 00:19 UTC, MichaelHinrichs commented on descriptions/Engine.Fase.md
> +It is an engine for sprites, tiles, and maps, made to interface with ZX Basic, C and ASM.
Ok mx minimalist.

2023-11-19 00:31 UTC, merged