add Autodesk FBX
SteamDatabase/FileDetectionRuleSets pull request #551
Opened 2023-11-21 10:30 UTC by diedyesterdaywashere

### SteamDB app page links to a few games using this

https://steamdb.info/app/49520/depots/

### Brief explanation of the change

added a rule for Autodesk FBX SDK

2023-11-23 21:31 UTC, Lifeismana requested changes
also needs some non matching tests

2023-11-23 21:31 UTC, Lifeismana commented on rules.ini
> +Autodesk_FBX = (?:|/)fbxsdk
to also match the unity plugin
```suggestion
Autodesk_FBX = fbxsdk
```

2023-11-23 21:31 UTC, Lifeismana commented on tests/types/SDK.Autodesk_FBX.txt
add this `Subnautica_Data/Plugins/x86_64/UnityFbxSdkNative.dll`
and run the generate strings script

2024-01-22 07:02 UTC, diedyesterdaywashere commented
![image](https://github.com/SteamDatabase/FileDetectionRuleSets/assets/81169193/16788de8-de96-49c9-a4dc-c2f54bbb8d92)

fixed it

2024-01-27 17:36 UTC, merged