Add iFAction Game Maker Engine
SteamDatabase/FileDetectionRuleSets pull request #778
Opened 2024-04-26 20:49 UTC by MichaelHinrichs

### SteamDB app page links to a few games using this
https://store.steampowered.com/app/2847250
https://store.steampowered.com/app/2281410
https://store.steampowered.com/app/1195270
https://store.steampowered.com/app/1593790

### Brief explanation of the change
Find the files from iFAction Game Maker.

2024-05-08 10:38 UTC, SteamTracker commented
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **Engine.iFAction\_Game\_Maker**

These apps now match: **(38)** [856060](https://steamdb.info/app/856060/depots/) [1195270](https://steamdb.info/app/1195270/depots/) [1346740](https://steamdb.info/app/1346740/depots/) [1371280](https://steamdb.info/app/1371280/depots/) [1380320](https://steamdb.info/app/1380320/depots/) [1381270](https://steamdb.info/app/1381270/depots/) [1388690](https://steamdb.info/app/1388690/depots/) [1397700](https://steamdb.info/app/1397700/depots/) [1401940](https://steamdb.info/app/1401940/depots/) [1405880](https://steamdb.info/app/1405880/depots/) [1442040](https://steamdb.info/app/1442040/depots/) [1493320](https://steamdb.info/app/1493320/depots/) [1522940](https://steamdb.info/app/1522940/depots/) [1568060](https://steamdb.info/app/1568060/depots/) [1593790](https://steamdb.info/app/1593790/depots/) [1606590](https://steamdb.info/app/1606590/depots/) [1633460](https://steamdb.info/app/1633460/depots/) [1751230](https://steamdb.info/app/1751230/depots/) [1894150](https://steamdb.info/app/1894150/depots/) [1936480](https://steamdb.info/app/1936480/depots/) [2012830](https://steamdb.info/app/2012830/depots/) [2078830](https://steamdb.info/app/2078830/depots/) [2081240](https://steamdb.info/app/2081240/depots/) [2084020](https://steamdb.info/app/2084020/depots/) [2094760](https://steamdb.info/app/2094760/depots/) [2102880](https://steamdb.info/app/2102880/depots/) [2136870](https://steamdb.info/app/2136870/depots/) [2228940](https://steamdb.info/app/2228940/depots/) [2269420](https://steamdb.info/app/2269420/depots/) [2281410](https://steamdb.info/app/2281410/depots/) [2320030](https://steamdb.info/app/2320030/depots/) [2343730](https://steamdb.info/app/2343730/depots/) [2446080](https://steamdb.info/app/2446080/depots/) [2483970](https://steamdb.info/app/2483970/depots/) [2687080](https://steamdb.info/app/2687080/depots/) [2767610](https://steamdb.info/app/2767610/depots/) [2847250](https://steamdb.info/app/2847250/depots/) [2875650](https://steamdb.info/app/2875650/depots/)

Please confirm that all these changed apps are correct.

2024-06-13 02:51 UTC, Lifeismana requested changes

2024-06-13 02:51 UTC, Lifeismana commented on descriptions/Engine.iFAction_Game_Maker.md
> +[**iFAction**](http://www.cedong.com.cn/index.html) is a visualized game making software.
needs a website in english

2024-06-13 02:51 UTC, Lifeismana commented on rules.ini
> +iFAction_Game_Maker[] = (?:^|/)iF(?:Con|ActionGame\.dll)$
```suggestion
iFAction_Game_Maker = (?:^|/)iFCon$
```

2024-06-24 19:32 UTC, MichaelHinrichs commented on descriptions/Engine.iFAction_Game_Maker.md
> +[**iFAction**](http://www.cedong.com.cn/index.html) is a visualized game making software.
There isn't one.

2024-09-02 14:10 UTC, SteamDB-Tracker commented
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **Engine.iFAction\_Game\_Maker**

These apps now match: **(39)** [856060](https://steamdb.info/app/856060/depots/) [1346740](https://steamdb.info/app/1346740/depots/) [1371280](https://steamdb.info/app/1371280/depots/) [1380320](https://steamdb.info/app/1380320/depots/) [1381270](https://steamdb.info/app/1381270/depots/) [1388690](https://steamdb.info/app/1388690/depots/) [1397700](https://steamdb.info/app/1397700/depots/) [1401940](https://steamdb.info/app/1401940/depots/) [1405880](https://steamdb.info/app/1405880/depots/) [1442040](https://steamdb.info/app/1442040/depots/) [1493320](https://steamdb.info/app/1493320/depots/) [1522940](https://steamdb.info/app/1522940/depots/) [1568060](https://steamdb.info/app/1568060/depots/) [1606590](https://steamdb.info/app/1606590/depots/) [1633460](https://steamdb.info/app/1633460/depots/) [1751230](https://steamdb.info/app/1751230/depots/) [1894150](https://steamdb.info/app/1894150/depots/) [1936480](https://steamdb.info/app/1936480/depots/) [2012830](https://steamdb.info/app/2012830/depots/) [2081240](https://steamdb.info/app/2081240/depots/) [2084020](https://steamdb.info/app/2084020/depots/) [2094760](https://steamdb.info/app/2094760/depots/) [2102880](https://steamdb.info/app/2102880/depots/) [2136870](https://steamdb.info/app/2136870/depots/) [2228940](https://steamdb.info/app/2228940/depots/) [2269420](https://steamdb.info/app/2269420/depots/) [2281410](https://steamdb.info/app/2281410/depots/) [2320030](https://steamdb.info/app/2320030/depots/) [2343730](https://steamdb.info/app/2343730/depots/) [2446080](https://steamdb.info/app/2446080/depots/) [2483970](https://steamdb.info/app/2483970/depots/) [2664850](https://steamdb.info/app/2664850/depots/) [2687080](https://steamdb.info/app/2687080/depots/) [2767610](https://steamdb.info/app/2767610/depots/) [2847250](https://steamdb.info/app/2847250/depots/) [2875650](https://steamdb.info/app/2875650/depots/) [2989460](https://steamdb.info/app/2989460/depots/) [3123630](https://steamdb.info/app/3123630/depots/) [3140700](https://steamdb.info/app/3140700/depots/)

Please confirm that all these changed apps are correct.

2024-09-02 14:48 UTC, Lifeismana commented
merged in 9904454fbe984aec2277a7b33f3e155d9c689c8c

2024-09-02 14:48 UTC, closed without merging