Add Double Fusion SDK
SteamDatabase/FileDetectionRuleSets pull request #815
Opened 2024-06-10 18:51 UTC by MichaelHinrichs

### SteamDB app page links to a few games using this
https://steamdb.info/app/1112400
https://steamdb.info/app/238010
https://steamdb.info/app/28050
https://steamdb.info/app/9480

### Brief explanation of the change
Detect DFEngine.dll.

2024-06-11 17:28 UTC, SteamTracker commented
After running changed rules in this pull request *(this bot only tests rules.ini changes)*:

Changed technologies: **SDK.Double\_Fusion**

These apps now match: **(14)** [7810](https://steamdb.info/app/7810/depots/) [9480](https://steamdb.info/app/9480/depots/) [10690](https://steamdb.info/app/10690/depots/) [21920](https://steamdb.info/app/21920/depots/) [28050](https://steamdb.info/app/28050/depots/) [29500](https://steamdb.info/app/29500/depots/) [29550](https://steamdb.info/app/29550/depots/) [33440](https://steamdb.info/app/33440/depots/) [201280](https://steamdb.info/app/201280/depots/) [238010](https://steamdb.info/app/238010/depots/) [880850](https://steamdb.info/app/880850/depots/) [1103800](https://steamdb.info/app/1103800/depots/) [1112400](https://steamdb.info/app/1112400/depots/) [1475570](https://steamdb.info/app/1475570/depots/)

Please confirm that all these changed apps are correct.

2024-06-13 02:21 UTC, Lifeismana requested changes

2024-06-13 02:21 UTC, Lifeismana commented on descriptions/SDK.Double_Fusion.md
> +The Double Fusion Engine in an in-game advertising engine.
needs a link

2024-09-04 21:22 UTC, Lifeismana commented
can't find a working version of their old website <http://doublefusion.com/> & this company seems to have died (not sure how much they have in common with Anzu)
Might get reopened if a working archive of their website gets found

2024-09-04 21:22 UTC, closed without merging